#!/bin/sh

ver=`perl -nE '/\@v([\d\.]+)/ and print $1 and exit' Dockerfile`
echo Building version $ver
docker build -t davorg/perl-perlanet:latest -t davorg/perl-perlanet:perlanet_$ver .
docker push -a docker.io/davorg/perl-perlanet
